export const themeProvider = {
  logoWidth: '190px',
  logoHeight: '35px',
  menuHeight: '70px',
  radius: '4px',
  // color guide
  primaryColor: 'green',
  headerBgColor: '#1b1c1d',
  sidebarBgColor: '#1b1c1d',
  btnCancelColor: '#db2828',
  btnActionColor: 'green',
  colorBlack: '#282828',
  colorWhite: '#ffffff',
  colorGreen: '#3fae29',
  colorGreenXxl: '#4cad32',
  colorDarkGreen: '#0e730f',
  colorGray: '#444444',
  colorGrayL: '#a1a1a1',
  colorGrayXl: '#dbdbdb',
  colorGrayXxl: '#f5f5f5',
  colorRed: '#f44336',
  colorDarkRed: '#d91a0c',
  colorYellow: '#ffdb00',
  colorYellowL: '#ffcd00',
  colorYellowXl: '#ffcd001a',
  colorYellowXxxl: '#fffae5',
  colorDarkYellow: '#fcdb4b',
  colorBlue: '#00b9e6',
  // font style
  fontFamilyBase: 'Roboto-Regular, Helvetica, sans-serif',
  fontRobotoMedium: 'Roboto-Medium',
  fontRobotoBold: 'Roboto-Bold',
  fontSizeSmall: '0.75rem',
  fontSizeBase: '1rem',
  fontSizeLarge: '1.25rem',
};
